# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xP-rVZonVWt9lGelrXfk-3I_Byt6RDhQ
"""

# =====================================
# INSTALL LIBRARIES
# =====================================


# =====================================
# IMPORT LIBRARIES
# =====================================
import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# =====================================
# PAGE CONFIG
# =====================================
st.set_page_config(page_title="Water Quality AI", layout="centered")

# =====================================
# TITLE
# =====================================
st.title("💧 AI-Based Water Quality Prediction")
st.write("This app predicts whether water is safe to drink and suggests purification methods.")

# =====================================
# LOAD DATA
# =====================================
@st.cache_data
def load_data():
    df = pd.read_csv("water_potability.csv")
    df.fillna(df.mean(), inplace=True)
    return df

df = load_data()

# =====================================
# TRAIN MODEL
# =====================================
@st.cache_resource
def train_model(data):
    X = data.drop("Potability", axis=1)
    y = data["Potability"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Accuracy
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    return model, X.columns, acc

model, feature_names, accuracy = train_model(df)

# =====================================
# SIDEBAR INPUT
# =====================================
st.sidebar.header("Enter Water Parameters")

def user_input():
    inputs = []
    for col in feature_names:
        val = st.sidebar.number_input(f"{col}", value=float(df[col].mean()))
        inputs.append(val)
    return pd.DataFrame([inputs], columns=feature_names)

input_df = user_input()

# =====================================
# DISPLAY INPUT
# =====================================
st.subheader("Input Parameters")
st.write(input_df)

# =====================================
# PREDICTION
# =====================================
if st.button("Predict Water Quality"):
    prediction = model.predict(input_df)[0]

    st.subheader("Result")

    if prediction == 1:
        st.success("✅ Water is SAFE to drink")
        st.info("💡 Suggestion: No treatment needed or basic filtration (sand + charcoal)")
    else:
        st.error("❌ Water is NOT SAFE")
        st.warning("💡 Suggestion: Use filtration + boiling + advanced purification")

# =====================================
# MODEL PERFORMANCE
# =====================================
st.subheader("Model Performance")
st.write(f"Accuracy: {round(accuracy * 100, 2)} %")

# =====================================
# OPTIONAL DATA VIEW
# =====================================
if st.checkbox("Show Dataset"):
    st.write(df.head())

# Kill any existing streamlit processes to free up port 8501
!pkill -f streamlit
import time
time.sleep(1) # Give some time for the process to terminate

# Start streamlit in the background, redirecting output to a file
# This way, it doesn't block the cell and its logs can be inspected if needed.

import time
import urllib.request
import re
import os

print("Waiting for Streamlit app to launch...")
time.sleep(5) # Give the app a few seconds to start

# Use localtunnel to create a public URL for port 8501
print("Attempting to create a public URL with localtunnel...")
# 'npx localtunnel' will automatically install localtunnel if not present
!npx localtunnel --port 8501 > localtunnel_output.log 2>&1 &

# Wait for localtunnel to establish connection and print its URL
time.sleep(5)

public_url = None
if os.path.exists('localtunnel_output.log'):
    with open('localtunnel_output.log', 'r') as f:
        localtunnel_log = f.read()

    match = re.search(r'your url is: (https://[^\n]+)', localtunnel_log)
    if match:
        public_url = match.group(1)

if public_url:
    print(f"Streamlit app is running at: {public_url}")
    print("Please open this URL in your web browser to interact with the app.")
else:
    print("Could not find public URL from localtunnel output.")
    print("Check 'streamlit_output.log' and 'localtunnel_output.log' for errors.")
    # Also print the logs for immediate debugging
    if os.path.exists('streamlit_output.log'):
        with open('streamlit_output.log', 'r') as f:
            print("--- Streamlit Output ---")
            print(f.read())
    if os.path.exists('localtunnel_output.log'):
        with open('localtunnel_output.log', 'r') as f:
            print("--- Localtunnel Output ---")
            print(f.read())

from google.colab import files
import os

# Check if the file already exists to avoid re-uploading unnecessarily
if not os.path.exists('water_potability.csv'):
    uploaded = files.upload()
    for fn in uploaded.keys():
        print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')
else:
    print('water_potability.csv already exists.')

import os

# Rename the uploaded file to the expected name
if os.path.exists('water_potability (1).csv'):
    os.rename('water_potability (1).csv', 'water_potability.csv')
    print('Renamed "water_potability (1).csv" to "water_potability.csv"')
elif not os.path.exists('water_potability.csv'):
    print('Error: "water_potability.csv" not found after upload.')
else:
    print('"water_potability.csv" already exists and is ready.')
